title: "Python Programming"
theme: minima

header_pages:
  - Notes.md

markdown: kramdown

repository: "https://github.com/successs404/python-programming-udemy"
github_icon: "images/github-icon.png"

plugins:
  - jemoji