title: "Python Programming"
theme: jekyll-theme-cayman

markdown: kramdown

repository: "https://github.com/successs404/python-programming-udemy"
github_icon: "images/github-icon.png"

plugins:
  - jemoji